CREATE SEQUENCE SEQ_MATCH_EVENT START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_PLAYER_STATS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

CREATE TABLE MATCH_EVENT (
    EVENT_ID        NUMBER          DEFAULT SEQ_MATCH_EVENT.NEXTVAL PRIMARY KEY,
    MATCH_ID        VARCHAR2(50)    NOT NULL REFERENCES MATCH_SCHEDULE(MATCH_ID),
    EVENT_TYPE      VARCHAR2(20)    NOT NULL CHECK (EVENT_TYPE IN ('GOAL', 'OWN_GOAL', 'PENALTY', 'ASSIST', 'YELLOW_CARD', 'RED_CARD', 'SUBSTITUTION')),
    PLAYER_ID       NUMBER          REFERENCES PLAYER(PLAYER_ID),
    ASSIST_PLAYER_ID NUMBER         REFERENCES PLAYER(PLAYER_ID),
    CLUB_ID         NUMBER          NOT NULL REFERENCES CLUB(CLUB_ID),
    MATCH_MINUTE    NUMBER,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE MATCH_EVENT IS '比赛事件表';
COMMENT ON COLUMN MATCH_EVENT.EVENT_TYPE IS 'GOAL=进球, OWN_GOAL=乌龙, PENALTY=点球, ASSIST=助攻, YELLOW_CARD=黄牌, RED_CARD=红牌, SUBSTITUTION=换人';
COMMENT ON COLUMN MATCH_EVENT.ASSIST_PLAYER_ID IS '助攻球员ID';
COMMENT ON COLUMN MATCH_EVENT.MATCH_MINUTE IS '比赛分钟数';

CREATE TABLE PLAYER_SEASON_STATS (
    STATS_ID        NUMBER          DEFAULT SEQ_PLAYER_STATS.NEXTVAL PRIMARY KEY,
    PLAYER_ID       NUMBER          NOT NULL REFERENCES PLAYER(PLAYER_ID),
    SEASON          VARCHAR2(20)    NOT NULL,
    LEAGUE          VARCHAR2(50)    NOT NULL,
    CLUB_ID         NUMBER          NOT NULL REFERENCES CLUB(CLUB_ID),
    GOALS           NUMBER          DEFAULT 0,
    ASSISTS         NUMBER          DEFAULT 0,
    YELLOW_CARDS    NUMBER          DEFAULT 0,
    RED_CARDS       NUMBER          DEFAULT 0,
    APPEARANCES     NUMBER          DEFAULT 0,
    MINUTES_PLAYED  NUMBER          DEFAULT 0,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UNIQUE (PLAYER_ID, SEASON, LEAGUE)
);

COMMENT ON TABLE PLAYER_SEASON_STATS IS '球员赛季统计表';
COMMENT ON COLUMN PLAYER_SEASON_STATS.APPEARANCES IS '出场次数';
COMMENT ON COLUMN PLAYER_SEASON_STATS.MINUTES_PLAYED IS '上场总分钟数';

CREATE INDEX IDX_MATCH_EVENT_MATCH ON MATCH_EVENT(MATCH_ID);
CREATE INDEX IDX_MATCH_EVENT_TYPE  ON MATCH_EVENT(EVENT_TYPE);
CREATE INDEX IDX_MATCH_EVENT_PLAYER ON MATCH_EVENT(PLAYER_ID);
CREATE INDEX IDX_PLAYER_STATS_SEASON ON PLAYER_SEASON_STATS(SEASON, LEAGUE);
CREATE INDEX IDX_PLAYER_STATS_PLAYER ON PLAYER_SEASON_STATS(PLAYER_ID);
CREATE INDEX IDX_PLAYER_STATS_GOALS ON PLAYER_SEASON_STATS(GOALS DESC);
CREATE INDEX IDX_PLAYER_STATS_ASSISTS ON PLAYER_SEASON_STATS(ASSISTS DESC);

COMMIT;
EXIT;
