-- 圈子功能增强
-- 1. 创建圈子表
CREATE TABLE CIRCLE (
    CIRCLE_ID       NUMBER          DEFAULT SEQ_CIRCLE.NEXTVAL PRIMARY KEY,
    CLUB_ID         NUMBER,
    NAME            VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    LOGO_URL        VARCHAR2(500),
    MEMBER_COUNT    NUMBER          DEFAULT 0,
    POST_COUNT      NUMBER          DEFAULT 0,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_CIRCLE_CLUB FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
    CONSTRAINT UK_CIRCLE_CLUB UNIQUE (CLUB_ID)
);

COMMENT ON TABLE CIRCLE IS '圈子表(每个俱乐部一个圈子)';
COMMENT ON COLUMN CIRCLE.CLUB_ID IS '关联俱乐部ID(为空表示主社区)';
COMMENT ON COLUMN CIRCLE.NAME IS '圈子名称';
COMMENT ON COLUMN CIRCLE.DESCRIPTION IS '圈子描述';
COMMENT ON COLUMN CIRCLE.MEMBER_COUNT IS '成员数';
COMMENT ON COLUMN CIRCLE.POST_COUNT IS '帖子数';

CREATE INDEX IDX_CIRCLE_CLUB ON CIRCLE(CLUB_ID);
CREATE INDEX IDX_CIRCLE_STATUS ON CIRCLE(STATUS);

-- 2. 创建圈子序列
CREATE SEQUENCE SEQ_CIRCLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 3. 修改帖子表，添加圈子ID和帖子类型字段
ALTER TABLE POST ADD CIRCLE_ID NUMBER;
ALTER TABLE POST ADD IS_PINNED NUMBER DEFAULT 0;
ALTER TABLE POST ADD IS_ESSENCE NUMBER DEFAULT 0;

COMMENT ON COLUMN POST.CIRCLE_ID IS '圈子ID(为空表示主社区)';
COMMENT ON COLUMN POST.IS_PINNED IS '是否置顶(0否1是)';
COMMENT ON COLUMN POST.IS_ESSENCE IS '是否精华帖(0否1是)';

ALTER TABLE POST ADD CONSTRAINT FK_POST_CIRCLE FOREIGN KEY (CIRCLE_ID) REFERENCES CIRCLE(CIRCLE_ID);

CREATE INDEX IDX_POST_CIRCLE ON POST(CIRCLE_ID);
CREATE INDEX IDX_POST_PINNED ON POST(IS_PINNED DESC, CREATED_AT DESC);
CREATE INDEX IDX_POST_ESSENCE ON POST(IS_ESSENCE DESC, CREATED_AT DESC);

-- 4. 创建圈子成员表
CREATE SEQUENCE SEQ_CIRCLE_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CIRCLE_MEMBER (
    MEMBER_ID       NUMBER          DEFAULT SEQ_CIRCLE_MEMBER.NEXTVAL PRIMARY KEY,
    CIRCLE_ID       NUMBER          NOT NULL,
    USER_ID         NUMBER          NOT NULL,
    JOINED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_CIRCLE_MEMBER UNIQUE (CIRCLE_ID, USER_ID),
    CONSTRAINT FK_CIRCLE_MEMBER_CIRCLE FOREIGN KEY (CIRCLE_ID) REFERENCES CIRCLE(CIRCLE_ID),
    CONSTRAINT FK_CIRCLE_MEMBER_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER(USER_ID)
);

COMMENT ON TABLE CIRCLE_MEMBER IS '圈子成员表';

CREATE INDEX IDX_CIRCLE_MEMBER_CIRCLE ON CIRCLE_MEMBER(CIRCLE_ID);
CREATE INDEX IDX_CIRCLE_MEMBER_USER ON CIRCLE_MEMBER(USER_ID);

COMMIT;
