UPDATE CIRCLE SET NAME = (SELECT c.NAME || ' 圈子' FROM CLUB c WHERE c.CLUB_ID = CIRCLE.CLUB_ID) WHERE CLUB_ID IS NOT NULL;
COMMIT;
SELECT CIRCLE_ID, CLUB_ID, NAME FROM CIRCLE WHERE ROWNUM <= 10;
EXIT;
