UPDATE CIRCLE SET DESCRIPTION = (SELECT c.NAME || ' 球迷圈子，欢迎加入讨论！' FROM CLUB c WHERE c.CLUB_ID = CIRCLE.CLUB_ID) WHERE CLUB_ID IS NOT NULL;
COMMIT;
SELECT CIRCLE_ID, NAME, DESCRIPTION FROM CIRCLE WHERE CLUB_ID = 7;
EXIT;
