-- 初始化球员赛季统计数据
-- 根据积分榜中的GOALS_FOR数据分配给各俱乐部球员

-- 首先清空现有数据
DELETE FROM PLAYER_SEASON_STATS;

-- 英超俱乐部球员统计 (俱乐部ID: 1-5)
-- Arsenal (club_id=1, goals_for=68)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 1,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(68 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(68 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(68 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(68 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(68 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(68 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 1 AND STATUS = 'ACTIVE';

-- Manchester City (club_id=2, goals_for=78)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 2,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(78 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(78 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(78 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(78 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(78 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(78 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 2 AND STATUS = 'ACTIVE';

-- Manchester United (club_id=3, goals_for=55)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 3,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(55 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(55 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(55 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(55 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(55 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(55 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 3 AND STATUS = 'ACTIVE';

-- Chelsea (club_id=4, goals_for=52)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 4,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(52 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(52 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(52 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(52 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(52 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(52 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 4 AND STATUS = 'ACTIVE';

-- Liverpool (club_id=5, goals_for=72)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 5,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(72 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(72 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(72 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(72 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(72 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(72 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 5 AND STATUS = 'ACTIVE';

-- 西甲俱乐部球员统计 (俱乐部ID: 6-10)
-- Barcelona (club_id=6, goals_for=85)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 6,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(85 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(85 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(85 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(85 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(85 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(85 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 6 AND STATUS = 'ACTIVE';

-- Real Madrid (club_id=7, goals_for=75)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 7,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(75 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(75 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(75 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(75 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(75 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(75 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 7 AND STATUS = 'ACTIVE';

-- Villarreal (club_id=8, goals_for=48)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 8,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(48 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(48 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(48 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(48 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(48 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(48 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 8 AND STATUS = 'ACTIVE';

-- Atletico Madrid (club_id=9, goals_for=58)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 9,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(58 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(58 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(58 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(58 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(58 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(58 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(5 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(2 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 9 AND STATUS = 'ACTIVE';

-- Real Sociedad (club_id=10, goals_for=45)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 10,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(45 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(45 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(45 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(45 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(45 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(45 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 10 AND STATUS = 'ACTIVE';

-- 法甲俱乐部球员统计 (俱乐部ID: 11-15)
-- PSG (club_id=11, goals_for=82)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 11,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(82 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(82 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(82 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(82 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(82 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(82 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 11 AND STATUS = 'ACTIVE';

-- Lyon (club_id=12, goals_for=55)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 12,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(55 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(55 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(55 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(55 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(55 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(55 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 12 AND STATUS = 'ACTIVE';

-- Monaco (club_id=13, goals_for=62)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 13,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(62 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(62 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(62 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(62 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(62 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(62 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 13 AND STATUS = 'ACTIVE';

-- Marseille (club_id=14, goals_for=58)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 14,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(58 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(58 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(58 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(58 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(58 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(58 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 14 AND STATUS = 'ACTIVE';

-- Rennes (club_id=15, goals_for=48)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 15,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(48 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(48 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(48 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(48 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(48 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(48 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 15 AND STATUS = 'ACTIVE';

-- 德甲俱乐部球员统计 (俱乐部ID: 16-20)
-- Bayern Munich (club_id=16, goals_for=92)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 16,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(92 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(92 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(92 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(92 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(92 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(92 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 16 AND STATUS = 'ACTIVE';

-- Borussia Dortmund (club_id=17, goals_for=68)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 17,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(68 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(68 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(68 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(68 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(68 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(68 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 17 AND STATUS = 'ACTIVE';

-- RB Leipzig (club_id=18, goals_for=58)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 18,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(58 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(58 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(58 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(58 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(58 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(58 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 18 AND STATUS = 'ACTIVE';

-- Stuttgart (club_id=19, goals_for=52)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 19,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(52 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(52 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(52 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(52 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(52 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(52 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 19 AND STATUS = 'ACTIVE';

-- Frankfurt (club_id=20, goals_for=48)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 20,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(48 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(48 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(48 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(48 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(48 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(48 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 20 AND STATUS = 'ACTIVE';

-- 意甲俱乐部球员统计 (俱乐部ID: 21-25)
-- AC Milan (club_id=21, goals_for=58)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 21,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(58 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(58 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(58 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(58 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(58 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(58 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 21 AND STATUS = 'ACTIVE';

-- Inter Milan (club_id=22, goals_for=72)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 22,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(72 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(72 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(72 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(72 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(72 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(72 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 22 AND STATUS = 'ACTIVE';

-- Napoli (club_id=23, goals_for=65)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 23,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(65 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(65 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(65 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(65 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(65 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(65 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 23 AND STATUS = 'ACTIVE';

-- Juventus (club_id=24, goals_for=55)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 24,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(55 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(55 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(55 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(55 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(55 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(55 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 24 AND STATUS = 'ACTIVE';

-- Lazio (club_id=25, goals_for=52)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 25,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(52 * 0.35 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(52 * 0.15 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(52 * 0.03 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(52 * 0.25 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        WHEN POSITION = 'MID' THEN FLOOR(52 * 0.20 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
        ELSE FLOOR(52 * 0.05 / NULLIF(COUNT(*) OVER (PARTITION BY POSITION), 0))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(4 + DBMS_RANDOM.VALUE(0, 3))
        WHEN POSITION = 'MID' THEN FLOOR(3 + DBMS_RANDOM.VALUE(0, 3))
        ELSE FLOOR(1 + DBMS_RANDOM.VALUE(0, 2))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE 
        WHEN POSITION = 'GK' THEN 30
        ELSE FLOOR(20 + DBMS_RANDOM.VALUE(0, 15))
    END,
    CASE 
        WHEN POSITION = 'GK' THEN 2700
        ELSE FLOOR(1200 + DBMS_RANDOM.VALUE(0, 1500))
    END
FROM PLAYER WHERE CLUB_ID = 25 AND STATUS = 'ACTIVE';

COMMIT;
