-- 简化版：直接更新球员进球数，确保与积分榜一致
-- 先清空现有数据
DELETE FROM PLAYER_SEASON_STATS;

-- 英超俱乐部
-- Arsenal (club_id=1, goals_for=68)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 1,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 18
                WHEN 2 THEN 12
                WHEN 3 THEN 5
                ELSE 1
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 8
                WHEN 2 THEN 6
                WHEN 3 THEN 4
                WHEN 4 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 3
                WHEN 2 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE 
        WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 12))
        WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8))
        ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3))
    END,
    CASE 
        WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6))
        WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5))
        ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3))
    END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 1 AND STATUS = 'ACTIVE';

-- Manchester City (club_id=2, goals_for=80)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 2,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 22
                WHEN 2 THEN 15
                WHEN 3 THEN 6
                ELSE 2
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 10
                WHEN 2 THEN 7
                WHEN 3 THEN 5
                WHEN 4 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 3
                WHEN 2 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(6, 14)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 4)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 2 AND STATUS = 'ACTIVE';

-- Manchester United (club_id=3, goals_for=48)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 3,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 14
                WHEN 2 THEN 8
                WHEN 3 THEN 4
                ELSE 1
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 6
                WHEN 2 THEN 4
                WHEN 3 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 7)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 3 AND STATUS = 'ACTIVE';

-- Chelsea (club_id=4, goals_for=58)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 4,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 16
                WHEN 2 THEN 10
                WHEN 3 THEN 4
                ELSE 1
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 7
                WHEN 2 THEN 5
                WHEN 3 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 11)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 4 AND STATUS = 'ACTIVE';

-- Liverpool (club_id=5, goals_for=74)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Premier League', 5,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 20
                WHEN 2 THEN 12
                WHEN 3 THEN 5
                ELSE 2
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 9
                WHEN 2 THEN 6
                WHEN 3 THEN 4
                WHEN 4 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 3
                WHEN 2 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(6, 13)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(4, 9)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 4)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 5 AND STATUS = 'ACTIVE';

-- 西甲俱乐部
-- Barcelona (club_id=6, goals_for=68)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 6,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 24
                WHEN 2 THEN 14
                WHEN 3 THEN 5
                ELSE 2
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 8
                WHEN 2 THEN 5
                WHEN 3 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(6, 14)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 4)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 6 AND STATUS = 'ACTIVE';

-- Real Madrid (club_id=7, goals_for=72)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 7,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 26
                WHEN 2 THEN 15
                WHEN 3 THEN 6
                ELSE 2
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 8
                WHEN 2 THEN 5
                WHEN 3 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(6, 14)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 4)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 7 AND STATUS = 'ACTIVE';

-- Villarreal (club_id=8, goals_for=45)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 8,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 14
                WHEN 2 THEN 8
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 7)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 8 AND STATUS = 'ACTIVE';

-- Atletico Madrid (club_id=9, goals_for=52)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 9,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 18
                WHEN 2 THEN 10
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 7)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(4, 7)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) ELSE FLOOR(DBMS_RANDOM.VALUE(1, 4)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 9 AND STATUS = 'ACTIVE';

-- Real Sociedad (club_id=10, goals_for=48)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'La Liga', 10,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 16
                WHEN 2 THEN 9
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 7)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 10 AND STATUS = 'ACTIVE';

-- 法甲俱乐部
-- PSG (club_id=11, goals_for=82)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 11,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 30
                WHEN 2 THEN 18
                WHEN 3 THEN 8
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 7
                WHEN 2 THEN 5
                WHEN 3 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(8, 16)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(5, 12)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 5)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 11 AND STATUS = 'ACTIVE';

-- Lyon (club_id=12, goals_for=48)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 12,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 16
                WHEN 2 THEN 9
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 7)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 12 AND STATUS = 'ACTIVE';

-- Monaco (club_id=13, goals_for=55)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 13,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 18
                WHEN 2 THEN 10
                ELSE 4
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 6
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 11)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 13 AND STATUS = 'ACTIVE';

-- Marseille (club_id=14, goals_for=52)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 14,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 17
                WHEN 2 THEN 10
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 11)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 14 AND STATUS = 'ACTIVE';

-- Rennes (club_id=15, goals_for=42)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Ligue 1', 15,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 14
                WHEN 2 THEN 8
                ELSE 2
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(4, 9)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 6)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 15 AND STATUS = 'ACTIVE';

-- 德甲俱乐部
-- Bayern Munich (club_id=16, goals_for=78)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 16,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 28
                WHEN 2 THEN 16
                WHEN 3 THEN 6
                ELSE 2
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 8
                WHEN 2 THEN 5
                WHEN 3 THEN 3
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(7, 14)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 4)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 16 AND STATUS = 'ACTIVE';

-- Borussia Dortmund (club_id=17, goals_for=58)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 17,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 20
                WHEN 2 THEN 12
                ELSE 4
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 6
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 12)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 17 AND STATUS = 'ACTIVE';

-- RB Leipzig (club_id=18, goals_for=62)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 18,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 20
                WHEN 2 THEN 12
                ELSE 4
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 7
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 12)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 18 AND STATUS = 'ACTIVE';

-- Stuttgart (club_id=19, goals_for=48)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 19,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 16
                WHEN 2 THEN 9
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(4, 10)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 7)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 19 AND STATUS = 'ACTIVE';

-- Frankfurt (club_id=20, goals_for=52)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Bundesliga', 20,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 17
                WHEN 2 THEN 10
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 11)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 20 AND STATUS = 'ACTIVE';

-- 意甲俱乐部
-- AC Milan (club_id=21, goals_for=55)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 21,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 18
                WHEN 2 THEN 10
                ELSE 4
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 6
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 11)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 21 AND STATUS = 'ACTIVE';

-- Inter Milan (club_id=22, goals_for=65)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 22,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 22
                WHEN 2 THEN 13
                ELSE 4
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 7
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(6, 13)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(4, 9)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 4)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 22 AND STATUS = 'ACTIVE';

-- Napoli (club_id=23, goals_for=58)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 23,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 20
                WHEN 2 THEN 12
                ELSE 4
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 6
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 12)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 23 AND STATUS = 'ACTIVE';

-- Juventus (club_id=24, goals_for=52)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 24,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 17
                WHEN 2 THEN 10
                ELSE 3
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 5
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 11)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 24 AND STATUS = 'ACTIVE';

-- Lazio (club_id=25, goals_for=58)
INSERT INTO PLAYER_SEASON_STATS (PLAYER_ID, SEASON, LEAGUE, CLUB_ID, GOALS, ASSISTS, YELLOW_CARDS, RED_CARDS, APPEARANCES, MINUTES_PLAYED)
SELECT PLAYER_ID, '2025-2026', 'Serie A', 25,
    CASE 
        WHEN POSITION = 'FW' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 20
                WHEN 2 THEN 12
                ELSE 4
            END
        WHEN POSITION = 'MID' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 6
                WHEN 2 THEN 4
                ELSE 2
            END
        WHEN POSITION = 'DF' THEN 
            CASE ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE)
                WHEN 1 THEN 2
                ELSE 1
            END
        ELSE 0
    END,
    CASE WHEN POSITION = 'FW' THEN FLOOR(DBMS_RANDOM.VALUE(5, 12)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(3, 8)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    CASE WHEN POSITION = 'DF' THEN FLOOR(DBMS_RANDOM.VALUE(3, 6)) WHEN POSITION = 'MID' THEN FLOOR(DBMS_RANDOM.VALUE(2, 5)) ELSE FLOOR(DBMS_RANDOM.VALUE(0, 3)) END,
    FLOOR(DBMS_RANDOM.VALUE(0, 2)),
    CASE WHEN POSITION = 'GK' THEN 30 ELSE FLOOR(DBMS_RANDOM.VALUE(15, 32)) END,
    CASE WHEN POSITION = 'GK' THEN 2700 ELSE FLOOR(DBMS_RANDOM.VALUE(800, 2500)) END
FROM PLAYER WHERE CLUB_ID = 25 AND STATUS = 'ACTIVE';

COMMIT;
