-- 社交功能数据库表
-- 用户关注、帖子、点赞、收藏、主队

-- 1. 给SYS_USER表添加新字段
ALTER TABLE SYS_USER ADD BIO VARCHAR2(500);
ALTER TABLE SYS_USER ADD FAVORITE_CLUB_ID NUMBER;

COMMENT ON COLUMN SYS_USER.BIO IS '个人简介';
COMMENT ON COLUMN SYS_USER.FAVORITE_CLUB_ID IS '主队ID(最喜欢的俱乐部)';

ALTER TABLE SYS_USER ADD CONSTRAINT FK_USER_FAVORITE_CLUB FOREIGN KEY (FAVORITE_CLUB_ID) REFERENCES CLUB(CLUB_ID);

-- 2. 创建序列
CREATE SEQUENCE SEQ_USER_FOLLOW START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POST_LIKE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POST_FAVORITE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 3. 用户关注表 USER_FOLLOW
CREATE TABLE USER_FOLLOW (
    FOLLOW_ID       NUMBER          DEFAULT SEQ_USER_FOLLOW.NEXTVAL PRIMARY KEY,
    FOLLOWER_ID     NUMBER          NOT NULL,
    FOLLOWING_ID    NUMBER          NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_USER_FOLLOW UNIQUE (FOLLOWER_ID, FOLLOWING_ID),
    CONSTRAINT FK_FOLLOWER FOREIGN KEY (FOLLOWER_ID) REFERENCES SYS_USER(USER_ID),
    CONSTRAINT FK_FOLLOWING FOREIGN KEY (FOLLOWING_ID) REFERENCES SYS_USER(USER_ID),
    CONSTRAINT CK_FOLLOW_SELF CHECK (FOLLOWER_ID != FOLLOWING_ID)
);

COMMENT ON TABLE USER_FOLLOW IS '用户关注表';
COMMENT ON COLUMN USER_FOLLOW.FOLLOWER_ID IS '关注者ID';
COMMENT ON COLUMN USER_FOLLOW.FOLLOWING_ID IS '被关注者ID';

CREATE INDEX IDX_USER_FOLLOW_FOLLOWER ON USER_FOLLOW(FOLLOWER_ID);
CREATE INDEX IDX_USER_FOLLOW_FOLLOWING ON USER_FOLLOW(FOLLOWING_ID);

-- 4. 帖子表 POST
CREATE TABLE POST (
    POST_ID         NUMBER          DEFAULT SEQ_POST.NEXTVAL PRIMARY KEY,
    USER_ID         NUMBER          NOT NULL,
    CONTENT         CLOB            NOT NULL,
    IMAGE_URLS      VARCHAR2(2000),
    CLUB_ID         NUMBER,
    LIKE_COUNT      NUMBER          DEFAULT 0,
    FAVORITE_COUNT  NUMBER          DEFAULT 0,
    COMMENT_COUNT   NUMBER          DEFAULT 0,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'HIDDEN', 'DELETED')),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_POST_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER(USER_ID),
    CONSTRAINT FK_POST_CLUB FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID)
);

COMMENT ON TABLE POST IS '帖子表';
COMMENT ON COLUMN POST.USER_ID IS '发帖用户ID';
COMMENT ON COLUMN POST.CONTENT IS '帖子内容';
COMMENT ON COLUMN POST.IMAGE_URLS IS '图片URL列表(JSON数组)';
COMMENT ON COLUMN POST.CLUB_ID IS '关联俱乐部ID(可选)';
COMMENT ON COLUMN POST.LIKE_COUNT IS '点赞数';
COMMENT ON COLUMN POST.FAVORITE_COUNT IS '收藏数';
COMMENT ON COLUMN POST.COMMENT_COUNT IS '评论数';

CREATE INDEX IDX_POST_USER ON POST(USER_ID);
CREATE INDEX IDX_POST_CREATED ON POST(CREATED_AT DESC);
CREATE INDEX IDX_POST_CLUB ON POST(CLUB_ID);

-- 5. 帖子点赞表 POST_LIKE
CREATE TABLE POST_LIKE (
    LIKE_ID         NUMBER          DEFAULT SEQ_POST_LIKE.NEXTVAL PRIMARY KEY,
    POST_ID         NUMBER          NOT NULL,
    USER_ID         NUMBER          NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_POST_LIKE UNIQUE (POST_ID, USER_ID),
    CONSTRAINT FK_LIKE_POST FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID),
    CONSTRAINT FK_LIKE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER(USER_ID)
);

COMMENT ON TABLE POST_LIKE IS '帖子点赞表';
COMMENT ON COLUMN POST_LIKE.POST_ID IS '帖子ID';
COMMENT ON COLUMN POST_LIKE.USER_ID IS '点赞用户ID';

CREATE INDEX IDX_POST_LIKE_POST ON POST_LIKE(POST_ID);
CREATE INDEX IDX_POST_LIKE_USER ON POST_LIKE(USER_ID);

-- 6. 帖子收藏表 POST_FAVORITE
CREATE TABLE POST_FAVORITE (
    FAVORITE_ID     NUMBER          DEFAULT SEQ_POST_FAVORITE.NEXTVAL PRIMARY KEY,
    POST_ID         NUMBER          NOT NULL,
    USER_ID         NUMBER          NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_POST_FAVORITE UNIQUE (POST_ID, USER_ID),
    CONSTRAINT FK_FAVORITE_POST FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID),
    CONSTRAINT FK_FAVORITE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER(USER_ID)
);

COMMENT ON TABLE POST_FAVORITE IS '帖子收藏表';
COMMENT ON COLUMN POST_FAVORITE.POST_ID IS '帖子ID';
COMMENT ON COLUMN POST_FAVORITE.USER_ID IS '收藏用户ID';

CREATE INDEX IDX_POST_FAVORITE_POST ON POST_FAVORITE(POST_ID);
CREATE INDEX IDX_POST_FAVORITE_USER ON POST_FAVORITE(USER_ID);

COMMIT;
