CREATE TABLE SEASON (
    SEASON_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LEAGUE VARCHAR2(100) NOT NULL,
    SEASON_NAME VARCHAR2(50) NOT NULL,
    START_YEAR VARCHAR2(4),
    END_YEAR VARCHAR2(4),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    TOTAL_ROUNDS NUMBER DEFAULT 38,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);