SET DEFINE OFF;
INSERT INTO SEASON (LEAGUE, SEASON_NAME, START_YEAR, END_YEAR, STATUS, TOTAL_ROUNDS) SELECT 'Bundesliga', '2025-2026', '2025', '2026', 'ACTIVE', 34 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SEASON WHERE LEAGUE = 'Bundesliga');
INSERT INTO SEASON (LEAGUE, SEASON_NAME, START_YEAR, END_YEAR, STATUS, TOTAL_ROUNDS) SELECT 'La Liga', '2025-2026', '2025', '2026', 'ACTIVE', 38 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SEASON WHERE LEAGUE = 'La Liga');
INSERT INTO SEASON (LEAGUE, SEASON_NAME, START_YEAR, END_YEAR, STATUS, TOTAL_ROUNDS) SELECT 'Ligue 1', '2025-2026', '2025', '2026', 'ACTIVE', 34 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SEASON WHERE LEAGUE = 'Ligue 1');
INSERT INTO SEASON (LEAGUE, SEASON_NAME, START_YEAR, END_YEAR, STATUS, TOTAL_ROUNDS) SELECT 'Premier League', '2025-2026', '2025', '2026', 'ACTIVE', 38 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SEASON WHERE LEAGUE = 'Premier League');
INSERT INTO SEASON (LEAGUE, SEASON_NAME, START_YEAR, END_YEAR, STATUS, TOTAL_ROUNDS) SELECT 'Serie A', '2025-2026', '2025', '2026', 'ACTIVE', 38 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SEASON WHERE LEAGUE = 'Serie A');
COMMIT;