-- ============================================================
-- SoccerHub 额外数据插入脚本
-- 用户、新闻、关注、评分、聊天消息
-- ============================================================

-- ============================================================
-- 第1部分: 用户数据
-- ============================================================

-- 超级管理员 (密码: admin123, BCrypt加密)
INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '系统管理员', 'admin@soccerhub.com', 'SUPER_ADMIN', 'ACTIVE');

-- 俱乐部管理员
INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS, MANAGED_CLUB_ID)
VALUES ('arsenal_admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '阿森纳管理员', 'arsenal@soccerhub.com', 'CLUB_ADMIN', 'ACTIVE', 1);

INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS, MANAGED_CLUB_ID)
VALUES ('madrid_admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '皇马管理员', 'madrid@soccerhub.com', 'CLUB_ADMIN', 'ACTIVE', 7);

-- 普通球迷用户
INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('zhangsan', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '张三', 'zhangsan@example.com', 'FAN', 'ACTIVE');

INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('lisi', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '李四', 'lisi@example.com', 'FAN', 'ACTIVE');

INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('wangwu', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '王五', 'wangwu@example.com', 'FAN', 'ACTIVE');

INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('zhaoliu', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '赵六', 'zhaoliu@example.com', 'FAN', 'ACTIVE');

INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('sunqi', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '孙七', 'sunqi@example.com', 'FAN', 'ACTIVE');

INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('zhouba', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '周八', 'zhouba@example.com', 'FAN', 'ACTIVE');

INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('wujiu', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '吴九', 'wujiu@example.com', 'FAN', 'ACTIVE');

INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, ROLE, STATUS)
VALUES ('chenshi', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '陈十', 'chenshi@example.com', 'FAN', 'ACTIVE');

-- ============================================================
-- 第2部分: 用户关注俱乐部
-- ============================================================

INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (3, 1, 1);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (3, 2, 0);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (4, 7, 1);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (4, 6, 0);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (5, 5, 1);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (5, 1, 0);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (6, 16, 1);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (6, 17, 0);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (7, 21, 1);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (7, 24, 0);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (8, 11, 1);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (8, 14, 0);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (9, 2, 1);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (10, 9, 1);
INSERT INTO USER_CLUB_FOLLOW (USER_ID, CLUB_ID, IS_PRIMARY) VALUES (11, 25, 1);

-- ============================================================
-- 第3部分: 评分记录
-- ============================================================

INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (3, 8, 'PLAYER', 9, '萨卡这赛季太强了！', 'MATCH', SYSTIMESTAMP - 1);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (3, 7, 'PLAYER', 8, '赖斯中场铁壁', 'MATCH', SYSTIMESTAMP - 1);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (4, 24, 'PLAYER', 10, '哈兰德进球机器！', 'MATCH', SYSTIMESTAMP - 2);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (4, 22, 'PLAYER', 9, '罗德里中场大师', 'MATCH', SYSTIMESTAMP - 2);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (5, 68, 'PLAYER', 9, '范戴克防守如铁壁！', 'MATCH', SYSTIMESTAMP - 3);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (6, 1, 'COACH', 9, '阿尔特塔战术革新！', 'GENERAL', SYSTIMESTAMP - 4);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (6, 2, 'COACH', 10, '瓜迪奥拉战术之神！', 'GENERAL', SYSTIMESTAMP - 4);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (7, 9, 'COACH', 9, '西蒙尼铁血教头！', 'GENERAL', SYSTIMESTAMP - 5);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (8, 11, 'COACH', 8, '恩里克进攻大师', 'GENERAL', SYSTIMESTAMP - 5);
INSERT INTO RATING_RECORD (USER_ID, TARGET_ID, TARGET_TYPE, SCORE, COMMENT_TEXT, RATING_TYPE, CREATED_AT)
VALUES (9, 16, 'COACH', 9, '孔帕尼年轻有为！', 'GENERAL', SYSTIMESTAMP - 6);

-- ============================================================
-- 第4部分: 聊天消息
-- ============================================================

INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (1, 3, 'Come on Arsenal! 枪手加油！', 'TEXT', SYSTIMESTAMP - INTERVAL '30' MINUTE);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (1, 3, '萨卡这赛季的表现简直是现象级的', 'TEXT', SYSTIMESTAMP - INTERVAL '20' MINUTE);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (2, 9, '曼城永远是最强的！哈兰德太猛了', 'TEXT', SYSTIMESTAMP - INTERVAL '2' HOUR);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (7, 4, 'Hala Madrid！皇马永远第一！', 'TEXT', SYSTIMESTAMP - INTERVAL '3' HOUR);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (6, 4, '巴萨加油！诺坎普永远是我们的家', 'TEXT', SYSTIMESTAMP - INTERVAL '4' HOUR);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (5, 5, 'You will never walk alone! 利物浦加油！', 'TEXT', SYSTIMESTAMP - INTERVAL '1' HOUR);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (16, 6, 'Mia San Mia! 拜仁最强！', 'TEXT', SYSTIMESTAMP - INTERVAL '5' HOUR);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (21, 7, 'Forza Inter! 蓝黑军团永远支持你！', 'TEXT', SYSTIMESTAMP - INTERVAL '6' HOUR);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (11, 8, 'Allez PSG! 巴黎加油！', 'TEXT', SYSTIMESTAMP - INTERVAL '7' HOUR);
INSERT INTO CLUB_CHAT_MESSAGE (CLUB_ID, USER_ID, CONTENT, MESSAGE_TYPE, CREATED_AT)
VALUES (9, 10, '马竞铁血精神！西蒙尼永远的神！', 'TEXT', SYSTIMESTAMP - INTERVAL '8' HOUR);

-- ============================================================
-- 第5部分: 新闻文章
-- ============================================================

INSERT INTO NEWS_ARTICLE (TITLE, SUMMARY, CONTENT, AUTHOR_ID, CLUB_ID, TAGS, VIEW_COUNT, IS_PUBLISHED, PUBLISHED_AT)
VALUES ('哈兰德帽子戏法！曼城4-1大胜拜仁', '欧冠四分之一决赛首回合，哈兰德上演帽子戏法，带领曼城在主场4-1大胜拜仁慕尼黑。', '在今晚进行的欧冠四分之一决赛首回合比赛中，曼城主场迎战拜仁慕尼黑。哈兰德在第12分钟、第34分钟和第78分钟各入一球，上演精彩的帽子戏法。德布劳内和罗德里在中场的控制力令人印象深刻，曼城全队展现出了极高的竞技水平。拜仁方面，穆西亚拉在第56分钟扳回一城，但最终未能改变败局。次回合比赛将于下周在慕尼黑进行。', 1, 2, '欧冠,哈兰德,曼城,拜仁', 12580, 1, SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO NEWS_ARTICLE (TITLE, SUMMARY, CONTENT, AUTHOR_ID, CLUB_ID, TAGS, VIEW_COUNT, IS_PUBLISHED, PUBLISHED_AT)
VALUES ('皇马3-1击败巴萨，国家德比再添经典', '西甲第30轮国家德比，皇马在伯纳乌球场3-1击败巴萨，继续领跑积分榜。', '在万众瞩目的西班牙国家德比中，皇家马德里凭借维尼修斯的梅开二度和贝林厄姆的进球，3-1击败了来访的巴塞罗那。巴萨方面仅由莱万多夫斯基扳回一球。这场胜利让皇马在西甲积分榜上的领先优势扩大到5分，争冠形势一片大好。', 1, 7, '国家德比,皇马,巴萨,西甲', 28930, 1, SYSTIMESTAMP - INTERVAL '2' DAY);

INSERT INTO NEWS_ARTICLE (TITLE, SUMMARY, CONTENT, AUTHOR_ID, CLUB_ID, TAGS, VIEW_COUNT, IS_PUBLISHED, PUBLISHED_AT)
VALUES ('利物浦2-1逆转阿森纳，安菲尔德再现奇迹', '英超第33轮，利物浦在安菲尔德2-1逆转阿森纳，萨拉赫传射建功。', '在安菲尔德的雨夜中，利物浦再次展现了永不放弃的精神。上半场阿森纳凭借萨卡的进球取得领先，但下半场萨拉赫先是助攻努涅斯扳平比分，随后自己打入制胜球。安菲尔德球迷高唱"你永远不会独行"，现场气氛令人动容。', 1, 5, '英超,利物浦,阿森纳,安菲尔德', 18920, 1, SYSTIMESTAMP - INTERVAL '3' DAY);

INSERT INTO NEWS_ARTICLE (TITLE, SUMMARY, CONTENT, AUTHOR_ID, CLUB_ID, TAGS, VIEW_COUNT, IS_PUBLISHED, PUBLISHED_AT)
VALUES ('国际米兰2-1力克AC米兰，米兰德比蓝黑胜出', '意甲第31轮米兰德比，国际米兰在圣西罗2-1击败AC米兰，继续紧追那不勒斯。', '米兰城的夜晚属于蓝黑色。国际米兰凭借劳塔罗·马丁内斯和巴雷拉的进球，2-1击败了同城对手AC米兰。AC米兰方面由莱奥扳回一城，但最终无力回天。这场胜利让国际米兰继续保持对榜首那不勒斯的压力，意甲争冠悬念依旧。', 1, 21, '米兰德比,国际米兰,AC米兰,意甲', 15670, 1, SYSTIMESTAMP - INTERVAL '4' DAY);

INSERT INTO NEWS_ARTICLE (TITLE, SUMMARY, CONTENT, AUTHOR_ID, CLUB_ID, TAGS, VIEW_COUNT, IS_PUBLISHED, PUBLISHED_AT)
VALUES ('巴黎圣日耳曼5-2狂胜马赛，法甲霸主地位不可撼动', '法甲第28轮，巴黎圣日耳曼在王子公园球场5-2大胜马赛，继续领跑法甲积分榜。', '巴黎圣日耳曼在主场展现了恐怖的攻击力，5-2横扫来访的马赛。登贝莱和巴尔科拉各入一球，阿森西奥梅开二度，穆阿尼锦上添花。马赛方面虽然由奥巴梅扬和云代尔各入一球，但面对巴黎的狂轰滥炸毫无还手之力。这场胜利让巴黎在法甲的领先优势达到12分。', 1, 11, '法甲,巴黎圣日耳曼,马赛', 9870, 1, SYSTIMESTAMP - INTERVAL '5' DAY);

INSERT INTO NEWS_ARTICLE (TITLE, SUMMARY, CONTENT, AUTHOR_ID, CLUB_ID, TAGS, VIEW_COUNT, IS_PUBLISHED, PUBLISHED_AT)
VALUES ('德甲综述：拜仁3-1多特蒙德，国家德比南大王胜出', '德甲第29轮国家德比，拜仁慕尼黑在安联竞技场3-1击败多特蒙德。', '德国国家德比如期上演，拜仁慕尼黑在安联竞技场3-1击败多特蒙德。凯恩、穆西亚拉和萨内分别为拜仁建功，多特蒙德仅由布兰特扳回一球。拜仁在德甲的统治力依旧不可撼动，多特蒙德虽然拼尽全力，但实力差距明显。', 1, 16, '德甲,拜仁,多特蒙德,国家德比', 13450, 1, SYSTIMESTAMP - INTERVAL '6' DAY);

INSERT INTO NEWS_ARTICLE (TITLE, SUMMARY, CONTENT, AUTHOR_ID, CLUB_ID, TAGS, VIEW_COUNT, IS_PUBLISHED, PUBLISHED_AT)
VALUES ('那不勒斯2-1逆转尤文图斯，意甲争冠白热化', '意甲第30轮焦点战，那不勒斯在马拉多纳球场2-1逆转尤文图斯。', '在马拉多纳球场的激情夜晚，那不勒斯展现了卫冕冠军的韧性。尤文图斯率先由弗拉霍维奇破门，但那不勒斯在下半场连入两球完成逆转。奥斯梅恩头球扳平，克瓦拉茨赫利亚在第87分钟打入绝杀。意甲争冠进入白热化阶段。', 1, 23, '意甲,那不勒斯,尤文图斯', 11230, 1, SYSTIMESTAMP - INTERVAL '7' DAY);

INSERT INTO NEWS_ARTICLE (TITLE, SUMMARY, CONTENT, AUTHOR_ID, CLUB_ID, TAGS, VIEW_COUNT, IS_PUBLISHED, PUBLISHED_AT)
VALUES ('英超争四白热化：切尔西1-0小胜曼联', '英超第34轮，切尔西凭借帕尔默的进球1-0小胜曼联，争四形势更加紧张。', '斯坦福桥的夜晚，切尔西和曼联展开了一场激烈的争四大战。最终，科尔·帕尔默在第67分钟的精彩远射决定了比赛胜负。切尔西凭借这场胜利暂时升至联赛第四，而曼联则距离前四越来越远。', 1, 4, '英超,切尔西,曼联,争四', 16780, 1, SYSTIMESTAMP - INTERVAL '8' DAY);

-- ============================================================
-- 第6部分: 审计日志
-- ============================================================

INSERT INTO AUDIT_LOG (USER_ID, ACTION_MODULE, ACTION_TYPE, TARGET_TYPE, TARGET_ID, IP_ADDRESS, ACTION_TIME)
VALUES (1, 'USER', 'LOGIN', 'USER', 1, '192.168.1.100', SYSTIMESTAMP - INTERVAL '1' HOUR);
INSERT INTO AUDIT_LOG (USER_ID, ACTION_MODULE, ACTION_TYPE, TARGET_TYPE, TARGET_ID, IP_ADDRESS, ACTION_TIME)
VALUES (1, 'PLAYER', 'CREATE', 'PLAYER', 1, '192.168.1.100', SYSTIMESTAMP - INTERVAL '2' HOUR);
INSERT INTO AUDIT_LOG (USER_ID, ACTION_MODULE, ACTION_TYPE, TARGET_TYPE, TARGET_ID, IP_ADDRESS, ACTION_TIME)
VALUES (2, 'CLUB', 'UPDATE', 'CLUB', 1, '192.168.1.101', SYSTIMESTAMP - INTERVAL '3' HOUR);
INSERT INTO AUDIT_LOG (USER_ID, ACTION_MODULE, ACTION_TYPE, TARGET_TYPE, TARGET_ID, IP_ADDRESS, ACTION_TIME)
VALUES (3, 'RATING', 'CREATE', 'PLAYER', 8, '192.168.1.102', SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO AUDIT_LOG (USER_ID, ACTION_MODULE, ACTION_TYPE, TARGET_TYPE, TARGET_ID, IP_ADDRESS, ACTION_TIME)
VALUES (4, 'RATING', 'CREATE', 'PLAYER', 24, '192.168.1.103', SYSTIMESTAMP - INTERVAL '2' DAY);

COMMIT;
