-- ============================================================
-- SoccerHub 数据库完整重置脚本
-- 步骤: DROP表 -> 重建表结构 -> 插入数据
-- ============================================================

-- 按依赖顺序删除所有表（CASCADE会自动删除约束）
DROP TABLE CLUB_CHAT_MESSAGE PURGE;
DROP TABLE RATING_RECORD PURGE;
DROP TABLE USER_CLUB_FOLLOW PURGE;
DROP TABLE TRANSFER_HISTORY_LOG PURGE;
DROP TABLE AUDIT_LOG PURGE;
DROP TABLE NEWS_ARTICLE PURGE;
DROP TABLE SYSTEM_DICTIONARY PURGE;
DROP TABLE LEAGUE_STANDINGS PURGE;
DROP TABLE MATCH_SCHEDULE PURGE;
DROP TABLE PLAYER PURGE;
DROP TABLE COACH PURGE;
DROP TABLE SYS_USER PURGE;
DROP TABLE CLUB PURGE;

-- 删除序列
DROP SEQUENCE SEQ_SYS_USER;
DROP SEQUENCE SEQ_CLUB;
DROP SEQUENCE SEQ_PLAYER;
DROP SEQUENCE SEQ_COACH;
DROP SEQUENCE SEQ_RATING;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_AUDIT;
DROP SEQUENCE SEQ_TRANSFER;
DROP SEQUENCE SEQ_DICTIONARY;
DROP SEQUENCE SEQ_NEWS;
DROP SEQUENCE SEQ_STANDINGS;

-- 重建序列
CREATE SEQUENCE SEQ_SYS_USER      START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_CLUB          START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_PLAYER        START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_COACH         START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_RATING        START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_MESSAGE       START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_AUDIT         START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_TRANSFER      START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_DICTIONARY    START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_NEWS          START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SEQ_STANDINGS     START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

-- ============================================================
-- 重建表结构
-- ============================================================

-- 3.1 SYS_USER
CREATE TABLE SYS_USER (
    USER_ID         NUMBER          DEFAULT SEQ_SYS_USER.NEXTVAL PRIMARY KEY,
    USERNAME        VARCHAR2(50)    NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(255)   NOT NULL,
    NICKNAME        VARCHAR2(100)   NOT NULL,
    EMAIL           VARCHAR2(100)   UNIQUE,
    AVATAR_URL      VARCHAR2(500),
    ROLE            VARCHAR2(20)    NOT NULL CHECK (ROLE IN ('FAN', 'CLUB_ADMIN', 'SUPER_ADMIN')),
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'BANNED', 'INACTIVE')),
    MANAGED_CLUB_ID NUMBER,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    LAST_LOGIN_AT   TIMESTAMP
);

-- 3.2 CLUB
CREATE TABLE CLUB (
    CLUB_ID           NUMBER          DEFAULT SEQ_CLUB.NEXTVAL PRIMARY KEY,
    NAME              VARCHAR2(100)   NOT NULL,
    SHORT_NAME        VARCHAR2(20),
    LEAGUE            VARCHAR2(50)    NOT NULL,
    CITY              VARCHAR2(100),
    COUNTRY           VARCHAR2(100),
    STADIUM           VARCHAR2(200),
    ESTABLISH_DATE    DATE,
    STADIUM_CAPACITY  NUMBER,
    LOGO_URL          VARCHAR2(500),
    DESCRIPTION       CLOB,
    TOTAL_SCORE       NUMBER(10,2)    DEFAULT 0,
    CREATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP
);

-- 3.3 PLAYER
CREATE TABLE PLAYER (
    PLAYER_ID      NUMBER          DEFAULT SEQ_PLAYER.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(100)   NOT NULL,
    NAME_CN         VARCHAR2(100),
    POSITION        VARCHAR2(20)   CHECK (POSITION IN ('GK', 'DF', 'MF', 'FW')),
    CLUB_ID         NUMBER          REFERENCES CLUB(CLUB_ID),
    JERSEY_NUMBER   NUMBER,
    NATIONALITY     VARCHAR2(100),
    BIRTH_DATE      DATE,
    HEIGHT_CM       NUMBER,
    WEIGHT_KG       NUMBER,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'RETIRED', 'INJURED', 'FREE')),
    MARKET_VALUE    NUMBER,
    AVATAR_URL      VARCHAR2(500),
    AVG_SCORE       NUMBER(4,2)     DEFAULT 0,
    TOTAL_RATINGS   NUMBER          DEFAULT 0,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP
);

-- 3.4 COACH
CREATE TABLE COACH (
    COACH_ID        NUMBER          DEFAULT SEQ_COACH.NEXTVAL PRIMARY KEY,
    NAME            VARCHAR2(100)   NOT NULL,
    NAME_CN         VARCHAR2(100),
    CLUB_ID         NUMBER          REFERENCES CLUB(CLUB_ID),
    IS_HEAD_COACH   NUMBER(1)       DEFAULT 0,
    NATIONALITY     VARCHAR2(100),
    BIRTH_DATE      DATE,
    AVATAR_URL      VARCHAR2(500),
    AVG_SCORE       NUMBER(4,2)     DEFAULT 0,
    TOTAL_RATINGS   NUMBER          DEFAULT 0,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP
);

-- 3.5 MATCH_SCHEDULE
CREATE TABLE MATCH_SCHEDULE (
    MATCH_ID        VARCHAR2(50)    PRIMARY KEY,
    HOME_CLUB_ID    NUMBER          NOT NULL REFERENCES CLUB(CLUB_ID),
    AWAY_CLUB_ID    NUMBER          NOT NULL REFERENCES CLUB(CLUB_ID),
    MATCH_TIME      TIMESTAMP       NOT NULL,
    HOME_SCORE      NUMBER,
    AWAY_SCORE      NUMBER,
    STATUS          VARCHAR2(20)    DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'IN_PROGRESS', 'FINISHED', 'CANCELLED')),
    ROUND           VARCHAR2(20),
    VENUE           VARCHAR2(200),
    REFEREE         VARCHAR2(100),
    LEAGUE          VARCHAR2(50),
    SEASON          VARCHAR2(20),
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_MATCH_CLUBS CHECK (HOME_CLUB_ID <> AWAY_CLUB_ID)
);

-- 3.6 USER_CLUB_FOLLOW
CREATE TABLE USER_CLUB_FOLLOW (
    USER_ID         NUMBER          NOT NULL REFERENCES SYS_USER(USER_ID),
    CLUB_ID         NUMBER          NOT NULL REFERENCES CLUB(CLUB_ID),
    IS_PRIMARY      NUMBER(1)       DEFAULT 0,
    FOLLOW_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (USER_ID, CLUB_ID)
);

-- 3.7 RATING_RECORD
CREATE TABLE RATING_RECORD (
    RECORD_ID       NUMBER          DEFAULT SEQ_RATING.NEXTVAL PRIMARY KEY,
    USER_ID         NUMBER          NOT NULL REFERENCES SYS_USER(USER_ID),
    TARGET_ID       NUMBER          NOT NULL,
    TARGET_TYPE     VARCHAR2(10)    NOT NULL CHECK (TARGET_TYPE IN ('PLAYER', 'COACH')),
    SCORE           NUMBER(2,0)     NOT NULL CHECK (SCORE >= 1 AND SCORE <= 10),
    COMMENT_TEXT    VARCHAR2(500),
    RATING_TYPE     VARCHAR2(20)    DEFAULT 'GENERAL' CHECK (RATING_TYPE IN ('MATCH', 'SEASON', 'GENERAL')),
    MATCH_ID        VARCHAR2(50)    REFERENCES MATCH_SCHEDULE(MATCH_ID),
    IS_COLLAPSED    NUMBER(1)       DEFAULT 0,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP
);

-- 3.8 CLUB_CHAT_MESSAGE
CREATE TABLE CLUB_CHAT_MESSAGE (
    MESSAGE_ID      NUMBER          DEFAULT SEQ_MESSAGE.NEXTVAL PRIMARY KEY,
    CLUB_ID         NUMBER          NOT NULL REFERENCES CLUB(CLUB_ID),
    USER_ID         NUMBER          NOT NULL REFERENCES SYS_USER(USER_ID),
    CONTENT         CLOB            NOT NULL,
    MESSAGE_TYPE    VARCHAR2(20)    DEFAULT 'TEXT' CHECK (MESSAGE_TYPE IN ('TEXT', 'IMAGE', 'LINK', 'SYSTEM')),
    IS_DELETED      NUMBER(1)       DEFAULT 0,
    IS_COLLAPSED    NUMBER(1)       DEFAULT 0,
    DELETED_BY      NUMBER,
    DELETED_AT      TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP
);

-- 3.9 TRANSFER_HISTORY_LOG
CREATE TABLE TRANSFER_HISTORY_LOG (
    LOG_ID          NUMBER          DEFAULT SEQ_TRANSFER.NEXTVAL PRIMARY KEY,
    PLAYER_ID       NUMBER          REFERENCES PLAYER(PLAYER_ID),
    OLD_CLUB_ID     NUMBER,
    NEW_CLUB_ID     NUMBER,
    TRANSFER_TYPE   VARCHAR2(20)    CHECK (TRANSFER_TYPE IN ('IN', 'OUT', 'LOAN', 'FREE')),
    TRANSFER_FEE    NUMBER,
    SEASON          VARCHAR2(20),
    ACTION_USER_ID  NUMBER          REFERENCES SYS_USER(USER_ID),
    ACTION_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    NOTES           VARCHAR2(500)
);

-- 3.10 SYSTEM_DICTIONARY
CREATE TABLE SYSTEM_DICTIONARY (
    DICT_ID         NUMBER          DEFAULT SEQ_DICTIONARY.NEXTVAL PRIMARY KEY,
    DICT_TYPE       VARCHAR2(50)    NOT NULL,
    DICT_KEY        VARCHAR2(100)   NOT NULL,
    DICT_VALUE      VARCHAR2(200)   NOT NULL,
    SORT_ORDER      NUMBER          DEFAULT 0,
    IS_ENABLED      NUMBER(1)       DEFAULT 1,
    DESCRIPTION     VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    UNIQUE (DICT_TYPE, DICT_KEY)
);

-- 3.11 AUDIT_LOG
CREATE TABLE AUDIT_LOG (
    LOG_ID          NUMBER          DEFAULT SEQ_AUDIT.NEXTVAL PRIMARY KEY,
    USER_ID         NUMBER,
    ACTION_MODULE   VARCHAR2(50),
    ACTION_TYPE     VARCHAR2(50),
    TARGET_TYPE     VARCHAR2(50),
    TARGET_ID       NUMBER,
    OLD_VALUE       CLOB,
    NEW_VALUE       CLOB,
    IP_ADDRESS      VARCHAR2(50),
    USER_AGENT      VARCHAR2(500),
    ACTION_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);

-- 3.12 LEAGUE_STANDINGS
CREATE TABLE LEAGUE_STANDINGS (
    STANDING_ID     NUMBER          DEFAULT SEQ_STANDINGS.NEXTVAL PRIMARY KEY,
    LEAGUE          VARCHAR2(50)    NOT NULL,
    SEASON          VARCHAR2(20)    NOT NULL,
    CLUB_ID         NUMBER          NOT NULL REFERENCES CLUB(CLUB_ID),
    POSITION        NUMBER,
    PLAYED          NUMBER          DEFAULT 0,
    WON             NUMBER          DEFAULT 0,
    DRAWN           NUMBER          DEFAULT 0,
    LOST            NUMBER          DEFAULT 0,
    GOALS_FOR       NUMBER          DEFAULT 0,
    GOALS_AGAINST   NUMBER          DEFAULT 0,
    GOAL_DIFF       NUMBER          DEFAULT 0,
    POINTS          NUMBER          DEFAULT 0,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UNIQUE (LEAGUE, SEASON, CLUB_ID)
);

-- 3.13 NEWS_ARTICLE
CREATE TABLE NEWS_ARTICLE (
    ARTICLE_ID      NUMBER          DEFAULT SEQ_NEWS.NEXTVAL PRIMARY KEY,
    TITLE           VARCHAR2(300)   NOT NULL,
    SUMMARY         VARCHAR2(500),
    CONTENT         CLOB            NOT NULL,
    SOURCE_URL      VARCHAR2(1000),
    SOURCE_NAME     VARCHAR2(100),
    AUTHOR_ID       NUMBER          REFERENCES SYS_USER(USER_ID),
    CLUB_ID         NUMBER          REFERENCES CLUB(CLUB_ID),
    TAGS            VARCHAR2(500),
    COVER_IMAGE_URL VARCHAR2(500),
    VIEW_COUNT      NUMBER          DEFAULT 0,
    IS_PUBLISHED    NUMBER(1)       DEFAULT 1,
    PUBLISHED_AT    TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP
);

-- ============================================================
-- 重建索引
-- ============================================================
CREATE INDEX IDX_PLAYER_CLUB     ON PLAYER(CLUB_ID);
CREATE INDEX IDX_PLAYER_STATUS   ON PLAYER(STATUS);
CREATE INDEX IDX_PLAYER_POSITION ON PLAYER(POSITION);
CREATE INDEX IDX_PLAYER_AVGSCORE ON PLAYER(AVG_SCORE DESC);
CREATE INDEX IDX_COACH_CLUB      ON COACH(CLUB_ID);
CREATE INDEX IDX_MATCH_TIME      ON MATCH_SCHEDULE(MATCH_TIME);
CREATE INDEX IDX_MATCH_LEAGUE    ON MATCH_SCHEDULE(LEAGUE);
CREATE INDEX IDX_MATCH_STATUS    ON MATCH_SCHEDULE(STATUS);
CREATE INDEX IDX_MATCH_HOME      ON MATCH_SCHEDULE(HOME_CLUB_ID);
CREATE INDEX IDX_MATCH_AWAY      ON MATCH_SCHEDULE(AWAY_CLUB_ID);
CREATE INDEX IDX_MATCH_LEAGUE_SEASON ON MATCH_SCHEDULE(LEAGUE, SEASON);
CREATE INDEX IDX_CHAT_CLUB       ON CLUB_CHAT_MESSAGE(CLUB_ID);
CREATE INDEX IDX_CHAT_TIME       ON CLUB_CHAT_MESSAGE(CREATED_AT DESC);
CREATE INDEX IDX_CHAT_CLUB_TIME  ON CLUB_CHAT_MESSAGE(CLUB_ID, CREATED_AT DESC);
CREATE INDEX IDX_RATING_TARGET   ON RATING_RECORD(TARGET_ID, TARGET_TYPE);
CREATE INDEX IDX_RATING_USER     ON RATING_RECORD(USER_ID);
CREATE INDEX IDX_RATING_CREATED  ON RATING_RECORD(CREATED_AT DESC);
CREATE INDEX IDX_FOLLOW_USER     ON USER_CLUB_FOLLOW(USER_ID);
CREATE INDEX IDX_FOLLOW_CLUB     ON USER_CLUB_FOLLOW(CLUB_ID);
CREATE INDEX IDX_AUDIT_TIME      ON AUDIT_LOG(ACTION_TIME DESC);
CREATE INDEX IDX_AUDIT_USER      ON AUDIT_LOG(USER_ID);
CREATE INDEX IDX_AUDIT_MODULE    ON AUDIT_LOG(ACTION_MODULE);
CREATE INDEX IDX_NEWS_PUBLISHED  ON NEWS_ARTICLE(PUBLISHED_AT DESC);
CREATE INDEX IDX_NEWS_CLUB       ON NEWS_ARTICLE(CLUB_ID);
CREATE INDEX IDX_NEWS_AUTHOR     ON NEWS_ARTICLE(AUTHOR_ID);
CREATE INDEX IDX_STANDINGS_LEAGUE ON LEAGUE_STANDINGS(LEAGUE, SEASON);
CREATE INDEX IDX_STANDINGS_POS   ON LEAGUE_STANDINGS(LEAGUE, SEASON, POSITION);

COMMIT;
